# Generated by Django 4.1.5 on 2023-02-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('student_email', models.CharField(max_length=30)),
                ('batch', models.IntegerField()),
                ('course', models.CharField(max_length=30)),
            ],
        ),
    ]
