# Generated by Django 4.1.5 on 2023-02-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('batch', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('re_password', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=100)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
